docker_builder:
  only_if: $CIRRUS_TAG !=~ "nightly/.*"
  env:
    TOKEN: ENCRYPTED[4b9a30c4a8e33fb0bad665362e5df532a227ff3acb36827d9f3618dea229d21a4726957e7a42067418a13a3cbf47af81]
    matrix:
      DEVICE: beta
      DEVICE: micro
  clone_script: 
    - git clone --recursive --branch=$CIRRUS_BRANCH https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git $CIRRUS_WORKING_DIR
    - git reset --hard $CIRRUS_CHANGE_IN_REPO
  make_script: ./makefiles/docker-make.sh DEVICE=$DEVICE
  test_script: ./makefiles/docker-make.sh DEVICE=$DEVICE test
  release_script: >
    if [ $CIRRUS_BRANCH = 'master' ]; then
      # compress the image
      xz -T $(nproc) build/axiom.img
      # get the github-release tool
      wget https://github.com/aktau/github-release/releases/download/v0.7.2/linux-amd64-github-release.tar.bz2
      tar -xf linux-amd64-github-release.tar.bz2
      # create the release and upload the compressed image
      ./bin/linux/amd64/github-release release -u $CIRRUS_REPO_OWNER -r $CIRRUS_REPO_NAME -t "nightly/$(git describe --always --abbrev=8)" -s $TOKEN -n "Nightly $(git describe --always --abbrev=8)" -c $CIRRUS_CHANGE_IN_REPO --pre-release -d " \
      A development snapshot of the axiom firmware.
      Build on $(date).

      \`\`\`diff
      - Warning! The nightly images are not veryfied by a human and might damage your camera permanently. 
      - Only continue, if you know, what you are doing!
      \`\`\`
      " || true
      ./bin/linux/amd64/github-release upload -u $CIRRUS_REPO_OWNER -r $CIRRUS_REPO_NAME -t "nightly/$(git describe --always --abbrev=8)" -s $TOKEN -n "axiom-$DEVICE-$(git describe --always --abbrev=8).img.xz" -f build/axiom.img.xz
    else
      echo "not on master branch; skipping deploy..."
    fi 
