image: ubuntu:16.04

stages:
  - build_qemu
  - release

before_script:
   - apt-get update -qq

build_qemu:
  stage: build_qemu
  script:
    - apt-get install -y -qq $(grep -vE "^\s*#" build_tools/dependencies.txt | tr "\n" " ") > /dev/null
    - build_tools/axiom_beta_build_image_Ubuntu.sh
  artifacts:
    paths:
      - quemu-xlnx.git/
  
  cache:
    untracked: true