image: jatha/axiom-build-container

stages:
  - build
  - assemble
  - test
  - deploy

variables:
  GIT_STRATEGY: clone
  GIT_CHECKOUT: "true"




# build the ROOT.fs and the BOOT.fs. Additionally build qemu for testing.
build_kernel:
  stage: build
  script:
    - make -f makefiles/host/main.mk -I makefiles/host -j -l $(nproc) build/linux-xlnx.git/arch/arm/boot/zImage
    - tar -cpf build/kernel_modules.tar build/kernel_modules.fs
  artifacts:
    paths:
      - build/linux-xlnx.git/arch/arm/boot/zImage
      - build/kernel_modules.tar
      - build/devicetree.dtb

build_u_boot:
  stage: build
  script:
    - make -f makefiles/host/main.mk -I makefiles/host build/u-boot-xlnx.git/u-boot.elf 
  artifacts:
    paths:
      - build/u-boot-xlnx.git/u-boot.elf

build_rootfs:
  stage: build
  script:
    - git checkout -B "$CI_COMMIT_REF_NAME" "$CI_COMMIT_SHA"
    - git branch --set-upstream-to=origin/$CI_COMMIT_REF_NAME $CI_COMMIT_REF_NAME
    - make -f makefiles/host/main.mk -I makefiles/host -j -l $(nproc) build/root.fs/etc/motd
    - tar -cpf build/rootfs.tar build/root.fs
  artifacts:
    paths:
      - build/rootfs.tar
  retry: 1

build_qemu:
  stage: build
  script:
    - make -f makefiles/host/main.mk -I makefiles/host -j -l $(nproc) build/qemu-xlnx.git/aarch64-softmmu/qemu-system-aarch64
  artifacts:
    paths:
      - build/qemu-xlnx.git


# assemble the parts to a single disk image
assemble_image:
  stage: assemble
  dependencies:
    - build_kernel
    - build_u_boot
    - build_rootfs
  script:
    - tar --same-owner -xf build/kernel_modules.tar
    - tar --same-owner -xf build/rootfs.tar
    - touch build/u-boot-xlnx.git/u-boot.elf build/root.fs/etc/motd build/linux-xlnx.git/arch/arm/boot/zImage build/axiom.img # hack to avoid rebuilding deps
    - make -f makefiles/host/main.mk -I makefiles/host -j -l $(nproc) build/axiom.img
  artifacts:
    name: "axiom-firmware-${CI_COMMIT_SHA}"
    paths:
      - build/axiom.img


# Test the image using qemu
test_qemu:
  stage: test
  dependencies:
    - build_qemu
    - build_u_boot
    - assemble_image
  script:
    - touch build/qemu-xlnx.git/aarch64-softmmu/qemu-system-aarch64 build/u-boot-xlnx.git/u-boot.elf build/axiom.img # hack to avoid rebuilding deps
    - make -f makefiles/host/main.mk -I makefiles/host -j -l $(nproc) ci-test
