language: generic

sudo: required

services:
  - docker
  
before_script:
  - sudo apt-get -qq update
  - sudo apt-get install -y realpath
  
script:
  - ./makefiles/docker_make.sh

after_script:
  - ./makefiles/docker_make.sh test
  
